parameters:
    # params

services:
    smart_information_systems_file.storage.configuration_container:
        class: SmartInformationSystems\FileBundle\Storage\ConfigurationContainer

    smart_information_systems_file.form.type.file:
        class: SmartInformationSystems\FileBundle\Form\Type\FileType
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@smart_information_systems_file.storage.configuration_container"
        tags:
            - { name: form.type, alias: sis_file_type }

    smart_information_systems_file.doctrine.prePersist:
        class: SmartInformationSystems\FileBundle\EventListener\DoctrineListener
        arguments:
            - "@smart_information_systems_file.storage.configuration_container"
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    smart_information_systems_file.twig.sis_file_extension:
        class: SmartInformationSystems\FileBundle\Twig\FileExtension
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@smart_information_systems_file.storage.configuration_container"
        tags:
            - { name: twig.extension }

    smart_information_systems_file.twig.sis_image_extension:
        class: SmartInformationSystems\FileBundle\Twig\ImageExtension
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@smart_information_systems_file.storage.configuration_container"
        tags:
            - { name: twig.extension }
